import Roboto from "next/font/local";
import "./globals.css";
import {AppProvider} from "@/../../src/components/AppContext";
import Header from "../components/layout/Header";
import { Toaster } from "react-hot-toast";

const robotoSans = Roboto({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "400 500 700",
});
const robotoMono = Roboto({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "400 500 700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}>
        <main className = "max-w-4xl mx-auto p-4">
        <AppProvider>
        <Toaster/>
        <Header />
        {children}
        <footer className="border-t p-8 text-center text-gray-500 mt-16">
          &copy; 2024 All rights reserved
       </footer>
       </AppProvider>
        </main>
      </body>
    </html>
  );
}
